baseURL: "https://derek-hardy.github.io"
title: Derek's Hub
copyright: "© [PaperMod Contributors](https://github.com/adityatelange/hugo-PaperMod/graphs/contributors)"
pagination:
  pagerSize: 5
theme: [paper-mod]

enableRobotsTXT: true
enableEmoji: true

minify:
  disableXML: true

params:
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowToc: true

  homeInfoParams:
    Title: Hi there 👋, @whoami
    Content: |
      * My name is Derek, I am a software engineer at **Goldman Sachs**, living in Singapore as a permanent resident 🇸🇬
      
      * 
      
      * My current project specialises in a Raft-based, API-driven **distributed scheduling platform** for batch workflows (think of Apache Airflow) 
       that takes care of around 30 million firmwide job executions daily
      
      *
      
      * Previously, I worked on the infrastructure supporting global Ad Network at **ByteDance**, making App monetization easy and accessible to all developers globally (BTW, the platform is called **Pangle**)
      
      *
      
      * 👉 [**More about me**](/Derek-Hub/about/)

  socialIcons:
    - name: LinkedIn
      title: View Profile on LinkedIn
      url: "https://www.linkedin.com/in/derekzhuang/"
    - name: Email
      title: Reach me via Email
      url: "mailto:derekzxj@outlook.com"

menu:
  main:
    - name: Posts
      url: posts/
      weight: 5
    - name: About
      url: about/
      weight: 10